# Generated by Django 4.2.7 on 2023-11-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
