# Generated by Django 4.2.7 on 2023-11-18 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_offer'),
        ('app', '0002_remove_category_deleted_at_remove_product_deleted_at_and_more'),
    ]

    operations = [
    ]
