# Generated by Django 4.2.7 on 2023-11-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_avg_rating_product_total_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avg_rating',
            field=models.FloatField(default=1),
        ),
    ]
