# Generated by Django 4.2.7 on 2023-12-02 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_ratings'),
        ('app', '0005_alter_product_avg_rating'),
    ]

    operations = [
    ]
