# Generated by Django 4.2.7 on 2023-11-25 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_verification_code'),
        ('accounts', '0003_rating'),
    ]

    operations = [
    ]
