# Generated by Django 4.2.7 on 2023-11-26 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_0003_profile_verification_code_0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
