# Generated by Django 4.2.7 on 2023-12-02 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_review'),
        ('accounts', '0004_merge_0003_profile_verification_code_0003_rating'),
    ]

    operations = [
    ]
