# Generated by Django 4.2.7 on 2023-11-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
